# Generated by Django 5.2.8 on 2025-11-13 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=225)),
                ('optionA', models.CharField(max_length=225)),
                ('optionB', models.CharField(max_length=225)),
                ('optionC', models.CharField(max_length=225)),
                ('optionD', models.CharField(max_length=225)),
                ('correctAnswer', models.CharField(choices=[('A', 'Lựa chọn A'), ('B', 'Lựa chọn B'), ('C', 'Lựa chọn C'), ('D', 'Lựa chọn D')], max_length=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.passage')),
            ],
            options={
                'unique_together': {('question', 'passage')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userAnswer', models.CharField(max_length=1)),
                ('isCorrect', models.BooleanField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.question')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
