# Generated by Django 5.2.8 on 2025-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
