# Generated by Django 5.2.8 on 2025-11-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_passage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.passage'),
        ),
    ]
