# Generated by Django 5.2.8 on 2025-11-16 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_remove_useranswer_explanation_question_explanation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correctAnswer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionA',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionB',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionC',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='optionD',
            new_name='option_d',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='isCorrect',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='userAnswer',
            new_name='user_answer',
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score_percentage', models.FloatField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.passage')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reading.quizattempt'),
        ),
    ]
