# Generated by Django 5.2.8 on 2025-11-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_rename_correctanswer_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text', 'passage')},
        ),
    ]
